# Netlify 설정 파일
[build]
  publish = "."   # 정적 파일 루트

# apex → www 리다이렉트 예시 (필요 시 주석 해제)
# [[redirects]]
#   from = "https://www.example.com/*"
#   to = "https://example.com/:splat"
#   status = 301
#   force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
